In [1]:
# !/usr/bin/python
# coding = utf-8
# Author: Selvaria

# 梯度的计算

import tensorflow as tf
print(tf.__version__)

# import os
# os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
# tf.test.is_gpu_available( cuda_only=False, min_cuda_compute_capability=None )

2.1.0


In [2]:
x = tf.reshape(tf.Variable(range(4), dtype=tf.float32),(4,1))
x

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.]], dtype=float32)>

In [4]:
# 举个例子：计算y=x**2在x = 3时的导数：

x = tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x) # watch函数的作用是把需要计算梯度的变量x加进来
    y = x * x

dy_dx = g.gradient(y, x) # y’ = 2*x = 2*3 = 6
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [6]:
x = tf.reshape(tf.Variable(range(4), dtype=tf.float32),(4,1))

with tf.GradientTape() as g:
    g.watch(x) # watch函数的作用是把需要计算梯度的变量x加进来，x必须是tf.Tensor格式，所以numpy不行，详见下个cell
    y = 2 * tf.matmul(tf.transpose(x), x) # matmul是矩阵乘法，transpose是转置，即两个向量的内积

dy_dx = g.gradient(y, x)
dy_dx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 0.],
       [ 4.],
       [ 8.],
       [12.]], dtype=float32)>

In [7]:
# numpy形式计算测试

import numpy as np

x = np.arange(0, 4).reshape(4, 1)
# x = tf.reshape(tf.Variable(range(4), dtype=tf.float32),(4,1))

with tf.GradientTape() as g:
    g.watch(x) # watch函数的作用是把需要计算梯度的变量x加进来
#     y = 2 * tf.matmul(tf.transpose(x), x)
    y = 2 * np.dot(x.T, x) #np.matmul()函数一样，dot是二维专用。转置T也一样是二维，高维度的用transpose

dy_dx = g.gradient(y, x)
dy_dx

ValueError: Passed in object of type <class 'numpy.ndarray'>, not tf.Tensor