In [1]:
# -*- coding:utf-8 -*-
# !/usr/bin/python
# Author: Selvaria

# 数据的读取和存储

import tensorflow as tf
import numpy as np
print(tf.__version__)

D:\Selvaria\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


2.0.0


In [2]:
# numpy的读取

import numpy as np

x = tf.ones(3)
np.save('x.npy', x)
x2 = np.load('x.npy')
x2

array([1., 1., 1.], dtype=float32)

In [3]:
# tensor的读取

y = tf.zeros(4)
np.save('xy.npy',[x,y])
x2, y2 = np.load('xy.npy', allow_pickle=True)
(x2, y2)

(<tf.Tensor: id=6, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>,
 <tf.Tensor: id=7, shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>)

In [4]:
# 读写模型的参数

class MLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = tf.keras.layers.Flatten()    # Flatten层将除第一维（batch_size）以外的维度展平
        self.dense1 = tf.keras.layers.Dense(units=256, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(units=10)

    def call(self, inputs):         
        x = self.flatten(inputs)   
        x = self.dense1(x)    
        output = self.dense2(x)     
        return output

net = MLP()
X = tf.random.normal((2,20))
Y = net(X)
Y

<tf.Tensor: id=69, shape=(2, 10), dtype=float32, numpy=
array([[-0.30569944,  0.03076953,  0.04277555, -0.03438187,  0.394513  ,
         0.2078364 , -0.59363496,  0.13228872, -0.07283815, -0.6509164 ],
       [ 0.2901893 , -0.6419499 ,  0.17273723, -0.33094716,  0.36129045,
        -0.12722564, -0.6842462 , -0.0793952 ,  0.18670055, -0.39737555]],
      dtype=float32)>

In [5]:
net.save_weights("4.5saved_model.h5")

In [6]:
# 如果调用储存好的参数， 那么模型得出的结果应该是一样的

net2 = MLP()
net2(X)
net2.load_weights("4.5saved_model.h5")
Y2 = net2(X)
Y2 == Y

<tf.Tensor: id=144, shape=(2, 10), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])>

In [7]:
# CPU/GPU设定，GPU需要有支持的显卡型号且安装tensorflow-gpu

gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
cpus = tf.config.experimental.list_physical_devices(device_type='CPU')
print("可用的GPU：",gpus,"\n可用的CPU：", cpus)

可用的GPU： [] 
可用的CPU： [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [8]:
# 可用的设备检查

from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 13352757937705102329
]


In [9]:
#

with tf.device('CPU:0'): # 指定特定的设备
    a = tf.constant([1,2,3],dtype=tf.float32)
    b = tf.random.uniform((3,))
    print(tf.exp(a + b) * 2)

tf.Tensor([14.471185 32.677216 44.25587 ], shape=(3,), dtype=float32)
